### ISSUE TITLE
Automatically include discovered taglibs when compiling

### ISSUE THREAD

**Issue by tigt** [marko-js/webpack#12]
Right now, the Webpack sample ships by externalizing `node_modules/` for the server build. But that results in errors like this when using dependency taglibs:

```
~/git/repo/node_modules/some-folder/components/Button/Button.marko:1
$ const { kind, renderBody, secondary, ...attrs } = input
  ^^^^^

SyntaxError: Unexpected token const
```

The fix could be dynamically updating `externals` like the following:

```js
// webpack.config.js
externals: [/^[^./!](?!.*\/node_modules\/some-taglib)/]
```

**Comment by DylanPiercey** [comment]
Right now the recommended pattern is to use `webpack-node-externals` like https://github.com/marko-js/examples/blob/master/examples/webpack-express/webpack.config.js#L82-L87. It allows you to not have to manually maintain this list with the config I just linked.

I don't think this is something we should be building into the plugin, at least not without a way to opt-out, since I feel it should be up to the user if they want their node_modules bundled or not on the server.

Curious if you are happy with the `webpack-node-externals` solution @tigt, or do you think we should basically ship with that as an option?

**Comment by tigt** [comment]
The regex is gnarly to understand, but I imagine it resists simplifying. It wouldn’t catch `.mjs`, but that’s easy enough to add.

It’s certainly better than the current <i lang="la">status quo</i>, so let’s do it.
